;; key
(define-key global-map (kbd "C-m") 'newline-and-indent)
(define-key global-map (kbd "C-i") 'indent-and-back-to-indentation)
(define-key global-map (kbd "C-j") 'indent-new-comment-line)
(define-key global-map (kbd "C-h") 'delete-backward-char)
(define-key global-map (kbd "C-t") 'other-window-or-split-horizontally)
(define-key global-map (kbd "C-w") 'copy-region-as-kill)
(define-key global-map (kbd "C-^") 'enlarge-window)
(define-key global-map (kbd "M-a") 'beginning-of-defun)
(define-key global-map (kbd "M-e") 'end-of-defun)
(define-key global-map (kbd "M-f") 'forward-sexp)
(define-key global-map (kbd "M-b") 'backward-sexp)
(define-key global-map (kbd "M-v") 'scroll-other-window)
(define-key global-map (kbd "M-$") 'replace-string)
(define-key global-map (kbd "M-?") 'help-for-help)
(define-key global-map (kbd "M-!") 'multi-term)
(define-key global-map (kbd "M-o") 'occur-by-moccur)
(define-key global-map (kbd "M-k") 'kill-this-buffer)
(define-key global-map (kbd "M-p") 'point-undo)
(define-key global-map (kbd "M-n") 'point-redo)
(define-key global-map (kbd "M-t") 'delete-window)
(define-key global-map (kbd "M-w") 'kill-region)
(define-key global-map (kbd "C-M-a") 'backward-sentence)
(define-key global-map (kbd "C-M-e") 'forward-sentence)
(define-key global-map (kbd "C-M-f") 'forward-word)
(define-key global-map (kbd "C-M-b") 'backward-word)
(define-key global-map (kbd "C-M-_") 'redo)
(define-key global-map (kbd "C-M-v") 'scroll-down)
(define-key global-map (kbd "C-M-$") 'replace-regexp)
(define-key global-map (kbd "C-x f") 'anything-find-file)
(define-key global-map (kbd "C-x b") 'list-buffers)
(define-key global-map (kbd "C-x ^") 'enlarge-window-horizontally)
(define-key global-map (kbd "C-x %") 'query-replace-regexp)
(define-key global-map (kbd "C-x $") 'replace-regexp)
(define-key global-map (kbd "C-x C-.") 'auto-complete)
(define-key global-map (kbd "C-x C-a") 'anything-recentf)
(define-key global-map (kbd "C-x C-c") 'server-edit)
(define-key global-map (kbd "C-x C-f") 'anything)
(define-key global-map (kbd "C-x C-b") 'switch-to-buffer)
(define-key global-map (kbd "C-x C-i") 'indent-region)
(define-key global-map (kbd "C-c C-t") 'twittering-mode)
(define-key global-map (kbd "C-c C-u") 'twittering-update-status-interactive)
(define-key global-map (kbd "C-z C-z") 'suspend-emacs)
(define-key global-map (kbd "C-<tab>") 'elscreen-next)
(define-key global-map (kbd "C-S-<tab>") 'elscreen-previous)
(define-key global-map (kbd "A-]") 'elscreen-next)
(define-key global-map (kbd "A-[") 'elscreen-previous)
(define-key global-map (kbd "A-}") 'elscreen-next)
(define-key global-map (kbd "A-{") 'elscreen-previous)
(define-key global-map (kbd "A-n") 'elscreen-create)
(define-key global-map (kbd "A-k") 'elscreen-kill)
