(mac-key-mode t)
(setq mac-control-modifier 'control)
(setq mac-command-modifier 'alt)
(setq mac-option-modifier 'meta)
(setq mac-pass-control-to-system nil)
(setq mac-pass-command-to-system nil)
(setq mac-pass-option-to-system nil)
